// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/KeyValueStore.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Orleans.Grpc.Shared.Services.Protos {
  public static partial class KeyValueStoreService
  {
    static readonly string __ServiceName = "KeyValueStore.KeyValueStoreService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Orleans.Grpc.Shared.Services.Protos.AddColumnRequest> __Marshaller_KeyValueStore_AddColumnRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Orleans.Grpc.Shared.Services.Protos.AddColumnRequest.Parser));
    static readonly grpc::Marshaller<global::Orleans.Grpc.Shared.Services.Protos.AddColumnReply> __Marshaller_KeyValueStore_AddColumnReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Orleans.Grpc.Shared.Services.Protos.AddColumnReply.Parser));

    static readonly grpc::Method<global::Orleans.Grpc.Shared.Services.Protos.AddColumnRequest, global::Orleans.Grpc.Shared.Services.Protos.AddColumnReply> __Method_AddColumn = new grpc::Method<global::Orleans.Grpc.Shared.Services.Protos.AddColumnRequest, global::Orleans.Grpc.Shared.Services.Protos.AddColumnReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddColumn",
        __Marshaller_KeyValueStore_AddColumnRequest,
        __Marshaller_KeyValueStore_AddColumnReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Orleans.Grpc.Shared.Services.Protos.KeyValueStoreReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of KeyValueStoreService</summary>
    [grpc::BindServiceMethod(typeof(KeyValueStoreService), "BindService")]
    public abstract partial class KeyValueStoreServiceBase
    {
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Orleans.Grpc.Shared.Services.Protos.AddColumnReply> AddColumn(global::Orleans.Grpc.Shared.Services.Protos.AddColumnRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for KeyValueStoreService</summary>
    public partial class KeyValueStoreServiceClient : grpc::ClientBase<KeyValueStoreServiceClient>
    {
      /// <summary>Creates a new client for KeyValueStoreService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public KeyValueStoreServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for KeyValueStoreService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public KeyValueStoreServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected KeyValueStoreServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected KeyValueStoreServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Orleans.Grpc.Shared.Services.Protos.AddColumnReply AddColumn(global::Orleans.Grpc.Shared.Services.Protos.AddColumnRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddColumn(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Orleans.Grpc.Shared.Services.Protos.AddColumnReply AddColumn(global::Orleans.Grpc.Shared.Services.Protos.AddColumnRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddColumn, null, options, request);
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Orleans.Grpc.Shared.Services.Protos.AddColumnReply> AddColumnAsync(global::Orleans.Grpc.Shared.Services.Protos.AddColumnRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddColumnAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Orleans.Grpc.Shared.Services.Protos.AddColumnReply> AddColumnAsync(global::Orleans.Grpc.Shared.Services.Protos.AddColumnRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddColumn, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override KeyValueStoreServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new KeyValueStoreServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(KeyValueStoreServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_AddColumn, serviceImpl.AddColumn).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, KeyValueStoreServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_AddColumn, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Orleans.Grpc.Shared.Services.Protos.AddColumnRequest, global::Orleans.Grpc.Shared.Services.Protos.AddColumnReply>(serviceImpl.AddColumn));
    }

  }
}
#endregion
